### ISSUE TITLE
Scala Steward job is failing for the repo

### ISSUE THREAD

**Issue by tgodzik** [brbrown25/testcontainers-scala-kafka-utils#10]
It seems that the sbt build is failing:
```
java.lang.IllegalArgumentException: requirement failed: Configurations already specified for module org.scalameta:munit:0.7.29:test
	at scala.Predef$.require(Predef.scala:281)
	at sbt.librarymanagement.DependencyBuilders.moduleIDConfigurable(DependencyBuilders.scala:30)
	at sbt.librarymanagement.DependencyBuilders.moduleIDConfigurable$(DependencyBuilders.scala:29)
	at sbt.package$.moduleIDConfigurable(package.scala:16)
	at Dependencies$.$anonfun$testDeps$1(Dependencies.scala:37)
	at scala.collection.immutable.List.map(List.scala:293)
	at Dependencies$.testDeps$lzycompute(Dependencies.scala:37)
	at Dependencies$.testDeps(Dependencies.scala:31)
	at $2a639f5576d54d295a98$.$anonfun$core$3(build.sbt:50)
	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:211)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[error] java.lang.IllegalArgumentException: requirement failed: Configurations already specified for module org.scalameta:munit:0.7.29:test
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

I see that the repo is not very active, but wanted to report it just in case

**Comment by brbrown25** [comment]
> It seems that the sbt build is failing:
> 
> ```
> 
> java.lang.IllegalArgumentException: requirement failed: Configurations already specified for module org.scalameta:munit:0.7.29:test
> 
> 	at scala.Predef$.require(Predef.scala:281)
> 
> 	at sbt.librarymanagement.DependencyBuilders.moduleIDConfigurable(DependencyBuilders.scala:30)
> 
> 	at sbt.librarymanagement.DependencyBuilders.moduleIDConfigurable$(DependencyBuilders.scala:29)
> 
> 	at sbt.package$.moduleIDConfigurable(package.scala:16)
> 
> 	at Dependencies$.$anonfun$testDeps$1(Dependencies.scala:37)
> 
> 	at scala.collection.immutable.List.map(List.scala:293)
> 
> 	at Dependencies$.testDeps$lzycompute(Dependencies.scala:37)
> 
> 	at Dependencies$.testDeps(Dependencies.scala:31)
> 
> 	at $2a639f5576d54d295a98$.$anonfun$core$3(build.sbt:50)
> 
> 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:211)
> 
> 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
> 
> 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
> 
> 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
> 
> 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
> 
> 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> 
> [error] java.lang.IllegalArgumentException: requirement failed: Configurations already specified for module org.scalameta:munit:0.7.29:test
> 
> [error] Use 'last' for the full log.
> 
> [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
> 
> ```
> 
> 
> 
> I see that the repo is not very active, but wanted to report it just in case
> 
> 

Thanks I will take a look into that!

**Comment by brbrown25** [comment]
@tgodzik I have added a commit that should fix this issue. Thanks for calling it to my attention.
